require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConceptualFieldsController do

  # This should return the minimal set of attributes required to create a valid
  # ConceptualField. As you add validations to ConceptualField, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConceptualFieldsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all conceptual_fields as @conceptual_fields" do
      conceptual_field = ConceptualField.create! valid_attributes
      get :index, {}, valid_session
      assigns(:conceptual_fields).should eq([conceptual_field])
    end
  end

  describe "GET show" do
    it "assigns the requested conceptual_field as @conceptual_field" do
      conceptual_field = ConceptualField.create! valid_attributes
      get :show, {:id => conceptual_field.to_param}, valid_session
      assigns(:conceptual_field).should eq(conceptual_field)
    end
  end

  describe "GET new" do
    it "assigns a new conceptual_field as @conceptual_field" do
      get :new, {}, valid_session
      assigns(:conceptual_field).should be_a_new(ConceptualField)
    end
  end

  describe "GET edit" do
    it "assigns the requested conceptual_field as @conceptual_field" do
      conceptual_field = ConceptualField.create! valid_attributes
      get :edit, {:id => conceptual_field.to_param}, valid_session
      assigns(:conceptual_field).should eq(conceptual_field)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ConceptualField" do
        expect {
          post :create, {:conceptual_field => valid_attributes}, valid_session
        }.to change(ConceptualField, :count).by(1)
      end

      it "assigns a newly created conceptual_field as @conceptual_field" do
        post :create, {:conceptual_field => valid_attributes}, valid_session
        assigns(:conceptual_field).should be_a(ConceptualField)
        assigns(:conceptual_field).should be_persisted
      end

      it "redirects to the created conceptual_field" do
        post :create, {:conceptual_field => valid_attributes}, valid_session
        response.should redirect_to(ConceptualField.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved conceptual_field as @conceptual_field" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConceptualField.any_instance.stub(:save).and_return(false)
        post :create, {:conceptual_field => {}}, valid_session
        assigns(:conceptual_field).should be_a_new(ConceptualField)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConceptualField.any_instance.stub(:save).and_return(false)
        post :create, {:conceptual_field => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested conceptual_field" do
        conceptual_field = ConceptualField.create! valid_attributes
        # Assuming there are no other conceptual_fields in the database, this
        # specifies that the ConceptualField created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ConceptualField.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => conceptual_field.to_param, :conceptual_field => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested conceptual_field as @conceptual_field" do
        conceptual_field = ConceptualField.create! valid_attributes
        put :update, {:id => conceptual_field.to_param, :conceptual_field => valid_attributes}, valid_session
        assigns(:conceptual_field).should eq(conceptual_field)
      end

      it "redirects to the conceptual_field" do
        conceptual_field = ConceptualField.create! valid_attributes
        put :update, {:id => conceptual_field.to_param, :conceptual_field => valid_attributes}, valid_session
        response.should redirect_to(conceptual_field)
      end
    end

    describe "with invalid params" do
      it "assigns the conceptual_field as @conceptual_field" do
        conceptual_field = ConceptualField.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConceptualField.any_instance.stub(:save).and_return(false)
        put :update, {:id => conceptual_field.to_param, :conceptual_field => {}}, valid_session
        assigns(:conceptual_field).should eq(conceptual_field)
      end

      it "re-renders the 'edit' template" do
        conceptual_field = ConceptualField.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConceptualField.any_instance.stub(:save).and_return(false)
        put :update, {:id => conceptual_field.to_param, :conceptual_field => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested conceptual_field" do
      conceptual_field = ConceptualField.create! valid_attributes
      expect {
        delete :destroy, {:id => conceptual_field.to_param}, valid_session
      }.to change(ConceptualField, :count).by(-1)
    end

    it "redirects to the conceptual_fields list" do
      conceptual_field = ConceptualField.create! valid_attributes
      delete :destroy, {:id => conceptual_field.to_param}, valid_session
      response.should redirect_to(conceptual_fields_url)
    end
  end

end
